version: "3"

services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/smartranking
    restart: always
    command: bash -c "npm install --only=prod"
    environment:
      - MONGO_URL=mongodb://mongo:27017/smartranking
    volumes:
      - ./dist/:/usr/src/smartranking/dist/
      - ./package.json:/usr/src/smartranking/package.json
    ports:
      - "3000:3000"
    links:
      - mongo